# Importing the Libraries

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import matplotlib
from sklearn import svm
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
from sklearn.metrics import accuracy_score


# Importing dataset

In [3]:
dataset=pd.read_csv('AMR_Dataset.csv')
dataset.head(20)

Patient_ID  Age Gender Infection_Source Condition      Infection_type  \
0     21610001   78      M      ET ASPIRATE  Critical   Hospital-acquired   
1     21610002   50      F              PUS    Stable   Hospital-acquired   
2     21610003   73      M            BLOOD    Stable   Hospital-acquired   
3     21610004   38      M           TISSUE    Stable   Hospital-acquired   
4     21610005   75      M       WOUND SWAB    Stable   Hospital-acquired   
5     21610006   78      M              PUS    Stable  Community-acquired   
6     21610007   24      F            BLOOD  Critical   Hospital-acquired   
7     21610008   59      M            BLOOD  Critical   Hospital-acquired   
8     21610009   59      M            BLOOD  Critical   Hospital-acquired   
9     21610010   49      M           SPUTUM    Stable   Hospital-acquired   
10    21610011   22      F              PUS    Stable  Community-acquired   
11    21610012   43      F           TISSUE  Critical   Hospital-acquired   
12    21610013    8      M            BLOOD    Stable   Hospital-acquired   
13    21610014   58      M      ET ASPIRATE  Critical   Hospital-acquired   
14    21610015   55      M              PUS    Stable   Hospital-acquired   
15    21610016   64      F       WOUND SWAB  Critical   Hospital-acquired   
16    21610017   64      F            BLOOD  Critical   Hospital-acquired   
17    21610018   64      F            BLOOD  Critical   Hospital-acquired   
18    21610019   41      F              PUS    Stable   Hospital-acquired   
19    21610020   52      M       WOUND SWAB    Stable  Community-acquired   

   Amikacin Aztreonam Levofloxacin Tigecycline Colistin Result  
0         R         R            R           R        I      R  
1         S         S            S           R        I      S  
2         R         R            R           R        I      R  
3         S         S            S           N        I      S  
4         S         R            R           R        I      R  
5         I         I            R           R        I      I  
6         N         N            S           N        I      N  
7         S         N            R           R        R      R  
8         S         N            R           R        R      R  
9         S         S            S           R        I      S  
10        S         R            R           R        I      R  
11        N         N            R           N        I      N  
12        S         R            R           R        I      R  
13        S         S            S           R        I      S  
14        I         R            R           R        I      R  
15        R         R            R           R        I      R  
16        N         N            R           N        I      N  
17        N         N            R           N        I      N  
18        S         I            S           R        I      N  
19        R         R            R           R        I      R

In [4]:
dataset.shape

(49, 12)

In [7]:
dataset['Infection_Source'].unique()


array(['ET ASPIRATE', 'PUS', 'BLOOD', 'TISSUE', 'WOUND SWAB', 'SPUTUM',
       'URINE', 'TRACHEAL ASPIRATE'], dtype=object)

In [8]:
dataset['Condition'].unique()

array(['Critical', 'Stable'], dtype=object)

In [9]:
dataset['Infection_type'].unique()

array(['Hospital-acquired', 'Community-acquired'], dtype=object)

In [10]:
dataset['Amikacin'].unique()

array(['R', 'S', 'I', 'N'], dtype=object)

# Replacing respective columns value with numeric value.

In [11]:
dataset['Gender'].replace({'M':'0','F':'1'},inplace=True)


In [12]:
dataset['Infection_Source'].replace({'ET ASPIRATE':'0','PUS':'1','BLOOD':'2','TISSUE':'3','WOUND SWAB':'4','SPUTUM':'5','URINE':'6','TRACHEAL ASPIRATE':'7'},inplace=True)


In [13]:
dataset['Condition'].replace({'Critical':'0','Stable':'1'},inplace=True)


In [14]:
dataset['Infection_type'].replace({'Hospital-acquired':'0','Community-acquired':'1'},inplace=True)

In [15]:
dataset.head(3)

Patient_ID  Age Gender Infection_Source Condition Infection_type Amikacin  \
0    21610001   78      0                0         0              0        R   
1    21610002   50      1                1         1              0        S   
2    21610003   73      0                2         1              0        R   

  Aztreonam Levofloxacin Tigecycline Colistin Result  
0         R            R           R        I      R  
1         S            S           R        I      S  
2         R            R           R        I      R

In [16]:
dataset['Amikacin'].replace({'R':'0','S':'1','I':'2','N':'3'},inplace=True)


In [17]:
dataset['Aztreonam'].replace({'R':'0','S':'1','I':'2','N':'3'},inplace=True)


In [18]:
dataset['Levofloxacin'].replace({'R':'0','S':'1','I':'2','N':'3'},inplace=True)


In [19]:
dataset['Tigecycline'].replace({'R':'0','S':'1','I':'2','N':'3'},inplace=True)

In [20]:
dataset['Colistin'].replace({'R':'0','S':'1','I':'2','N':'3'},inplace=True)

In [21]:
dataset['Result'].replace({'R':'0','S':'1','I':'2','N':'3'},inplace=True)

In [22]:
dataset.head(10)

Patient_ID  Age Gender Infection_Source Condition Infection_type Amikacin  \
0    21610001   78      0                0         0              0        0   
1    21610002   50      1                1         1              0        1   
2    21610003   73      0                2         1              0        0   
3    21610004   38      0                3         1              0        1   
4    21610005   75      0                4         1              0        1   
5    21610006   78      0                1         1              1        2   
6    21610007   24      1                2         0              0        3   
7    21610008   59      0                2         0              0        1   
8    21610009   59      0                2         0              0        1   
9    21610010   49      0                5         1              0        1   

  Aztreonam Levofloxacin Tigecycline Colistin Result  
0         0            0           0        2      0  
1         1            1           0        2      1  
2         0            0           0        2      0  
3         1            1           3        2      1  
4         0            0           0        2      0  
5         2            0           0        2      2  
6         3            1           3        2      3  
7         3            0           0        0      0  
8         3            0           0        0      0  
9         1            1           0        2      1

# Spliting the Dataset for all Antibiotics

In [23]:
X=dataset.drop(['Patient_ID','Result'],axis='columns')
X.head(10)

Age Gender Infection_Source Condition Infection_type Amikacin Aztreonam  \
0   78      0                0         0              0        0         0   
1   50      1                1         1              0        1         1   
2   73      0                2         1              0        0         0   
3   38      0                3         1              0        1         1   
4   75      0                4         1              0        1         0   
5   78      0                1         1              1        2         2   
6   24      1                2         0              0        3         3   
7   59      0                2         0              0        1         3   
8   59      0                2         0              0        1         3   
9   49      0                5         1              0        1         1   

  Levofloxacin Tigecycline Colistin  
0            0           0        2  
1            1           0        2  
2            0           0        2  
3            1           3        2  
4            0           0        2  
5            0           0        2  
6            1           3        2  
7            0           0        0  
8            0           0        0  
9            1           0        2

In [24]:
y=dataset['Result']
y.head(3)

0    0
1    1
2    0
Name: Result, dtype: object

In [25]:
## Splitting of data for training and testing

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=10)

 

In [26]:
import warnings
warnings.filterwarnings("ignore")

# Train our model with Multinomial Logistic regression

In [27]:
#Splitting of data for training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=10)

In [28]:
#Importing our Model.
from sklearn.linear_model import LogisticRegression
My_LR=LogisticRegression()


In [29]:
My_LR.fit(X_train, y_train)

LogisticRegression()

In [30]:
y_pred=My_LR.predict(X_test)

In [31]:
X.columns

Index(['Age', 'Gender', 'Infection_Source', 'Condition', 'Infection_type',
       'Amikacin', 'Aztreonam', 'Levofloxacin', 'Tigecycline', 'Colistin'],
      dtype='object')

In [32]:
#Predicting the new data.
My_LR.predict([[24,0,0,1,0,0,0,0,1,0]])

array(['0'], dtype=object)

In [132]:
My_LR.score(X_test,y_test)

0.5

In [ ]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)

scores=cross_val_score(LogisticRegression(), X, y, cv=cv)
print(scores)

[0.8 0.6 0.5 0.5 0.6]


In [180]:
avg_score = np.mean(scores)
print(avg_score)

0.6


In [178]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.75      0.86         4
           1       0.00      0.00      0.00         3
           3       0.33      0.67      0.44         3

    accuracy                           0.50        10
   macro avg       0.44      0.47      0.43        10
weighted avg       0.50      0.50      0.48        10



In [179]:
from sklearn.metrics import confusion_matrix
My_confusion_matrix = confusion_matrix(y_test,y_pred)
My_confusion_matrix

array([[3, 0, 1],
       [0, 0, 3],
       [0, 1, 2]], dtype=int64)

# Importing new data to predict.

In [ ]:
input_data= (24,1,2,1,0,0,2,2,2,2)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = My_LR.predict(input_data_reshaped)
print(prediction)


if (prediction[0] == '0'):
    print('The person is Resistance to the Antibiotic.')
elif (prediction[0] == '1'):
    print('The person is sensitive to the Antibiotic.')
elif (prediction[0] == '2'):
    print('The person is intermediate to the Antibiotic.')
else:
    print('The person Unknown to the Antibiotic.')

# Importing our trained model into a pickle file.

In [ ]:
import pickle

In [ ]:
filename = 'trained_model_All.sav'
pickle.dump(My_LR, open(filename, 'wb'))

In [ ]:
# loading the saved model
loaded_model = pickle.load(open('trained_model_all.sav', 'rb'))

In [ ]:
input_data = (24,0,0,1,2,2,2,2,2,2)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = loaded_model.predict(input_data_reshaped)
print(prediction)

if (prediction == '0'):
    print('The person is Resistance to the Antibiotic.')
elif (prediction == '1'):
    print('The person is sensitive to the Antibiotic.')
elif (prediction == '2'):
    print('The person is intermediate to the Antibiotic.')
else:
    print('The person Unknown to the Antibiotic.')

# 1.Spliting the Dataset for Amikacin

In [227]:
X1=dataset.drop(['Result','Patient_ID','Amikacin','Aztreonam','Levofloxacin','Tigecycline','Colistin'],axis='columns')
X1.head(3)

Age Gender Infection_Source Condition Infection_type
0   78      0                0         0              0
1   50      1                1         1              0
2   73      0                2         1              0

In [228]:
y1=dataset['Amikacin']
y1.head(3)

0    0
1    1
2    0
Name: Amikacin, dtype: object

In [229]:
## Splitting of data for training and testing

from sklearn.model_selection import train_test_split
X1_train, X1_test, y1_train, y1_test = train_test_split(X1,y1,test_size=0.2,random_state=10)

 

In [230]:
# Train our model with Logistic regression (Amikacin)

In [231]:
from sklearn.linear_model import LogisticRegression
My_LR1=LogisticRegression()

In [232]:
My_LR1.fit(X1_train, y1_train)

LogisticRegression()

In [240]:
y_pred1=My_LR1.predict(X1_test)

In [241]:
My_LR1.predict([[55,1,2,2,2,]])

array(['0'], dtype=object)

In [242]:
My_LR1.score(X1_test,y1_test)

0.6

In [243]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)

scores1=cross_val_score(LogisticRegression(), X1, y1, cv=cv)
print(scores)

[0.8 0.6 0.5 0.5 0.6]


In [244]:
avg_score = np.mean(scores1)
print(avg_score)

0.5800000000000001


In [245]:
from sklearn.metrics import classification_report
print(classification_report(y1_test,y_pred1))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.71      0.83      0.77         6
           3       0.50      1.00      0.67         1

    accuracy                           0.60        10
   macro avg       0.40      0.61      0.48        10
weighted avg       0.48      0.60      0.53        10



# Importing our trained model into a pickle file (Amikacin)

In [ ]:
filename = 'trained_model_Amikacin.sav'
pickle.dump(My_LR1, open(filename, 'wb'))

In [ ]:
# loading the saved model
loaded_model_1 = pickle.load(open('trained_model_Amikacin.sav', 'rb'))


In [ ]:
input_data = (24,0,0,1,1)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction1 = loaded_model_1.predict(input_data_reshaped)
print(prediction1)

if (prediction1[0] == '0'):
    print('The person is Resistance to the Antibiotic.')
elif (prediction1[0] == '1'):
    print('The person is sensitive to the Antibiotic.')
elif (prediction1[0] == '2'):
    print('The person is intermediate to the Antibiotic.')
else:
    print('The person Unknown to the Antibiotic.')

# 2.Spliting the Dataset for Aztreonam 

In [ ]:
X2=dataset.drop(['Result','Patient_ID','Amikacin','Aztreonam','Levofloxacin','Tigecycline','Colistin'],axis='columns')
X2.head(3)

In [ ]:
y2=dataset['Aztreonam']
y2.head(3)

In [ ]:
## Splitting of data for training and testing

from sklearn.model_selection import train_test_split
X2_train, X2_test, y2_train, y2_test = train_test_split(X2,y2,test_size=0.2,random_state=10)

 

# Train our model with Multiclass Logistic regression (Aztreonam)

In [266]:
from sklearn.linear_model import LogisticRegression
My_LR2=LogisticRegression()
My_LR2.fit(X2_train, y2_train)

LogisticRegression()

In [267]:
y_pred2=My_LR2.predict(X2_test)

In [270]:
My_LR2.predict([[55,1,2,2,2]])

array(['0'], dtype=object)

In [271]:
My_LR2.score(X2_test,y2_test)

0.4

In [272]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)

scores2=cross_val_score(LogisticRegression(), X2, y2, cv=cv)
print(scores)

[0.8 0.6 0.5 0.5 0.6]


In [273]:
avg_score = np.mean(scores2)
print(avg_score)

0.21999999999999997


In [274]:
from sklearn.metrics import classification_report
print(classification_report(y2_test,y_pred2))

              precision    recall  f1-score   support

           0       0.25      0.25      0.25         4
           1       0.67      0.50      0.57         4
           3       0.33      0.50      0.40         2

    accuracy                           0.40        10
   macro avg       0.42      0.42      0.41        10
weighted avg       0.43      0.40      0.41        10




# Importing our trained model into a pickle file (Aztreonam)

In [189]:
filename = 'trained_model_Aztreonam.sav'
pickle.dump(My_LR2, open(filename, 'wb'))

In [190]:
# loading the saved model
loaded_model_2 = pickle.load(open('trained_model_Aztreonam.sav', 'rb'))

In [191]:
input_data = (24,0,0,1,2)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction2 = loaded_model_2.predict(input_data_reshaped)
print(prediction)

if (prediction2[0] == '0'):
    print('The person is Resistance to the Antibiotic.')
elif (prediction2[0] == '1'):
    print('The person is sensitive to the Antibiotic.')
elif (prediction2[0] == '2'):
    print('The person is intermediate to the Antibiotic.')
else:
    print('The person Unknown to the Antibiotic.')

['3']
The person is Resistance to the Antibiotic.


# 3.Spliting the Dataset for Levofloxacin 

In [192]:
X3=dataset.drop(['Result','Patient_ID','Amikacin','Aztreonam','Levofloxacin','Tigecycline','Colistin'],axis='columns')
X3.head(3)

Age Gender Infection_Source Condition Infection_type
0   78      0                0         0              0
1   50      1                1         1              0
2   73      0                2         1              0

In [193]:
y3=dataset['Levofloxacin']
y3.head(3)

0    0
1    1
2    0
Name: Levofloxacin, dtype: object

In [258]:
## Splitting of data for training and testing

from sklearn.model_selection import train_test_split
X3_train, X3_test, y3_train, y3_test = train_test_split(X3,y3,test_size=0.2,random_state=10)

 

# Train our model with Multiclass Logistic regression (Levofloxacin )

In [282]:
from sklearn.linear_model import LogisticRegression
My_LR3=LogisticRegression()
My_LR3.fit(X3_train, y3_train)

LogisticRegression()

In [283]:
y_pred3=My_LR3.predict(X3_test)

In [284]:
My_LR3.predict([[55,1,2,2,2]])

array(['0'], dtype=object)

In [285]:
My_LR3.score(X3_test,y3_test)

0.5

In [286]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)

scores3=cross_val_score(LogisticRegression(), X3, y3, cv=cv)
print(scores)

[0.8 0.6 0.5 0.5 0.6]


In [287]:
avg_score = np.mean(scores3)
print(avg_score)

0.36


In [295]:
from sklearn.metrics import classification_report
print(classification_report(y3_test,y_pred3))

              precision    recall  f1-score   support

           0       0.43      0.75      0.55         4
           1       0.67      0.40      0.50         5
           2       0.00      0.00      0.00         1

    accuracy                           0.50        10
   macro avg       0.37      0.38      0.35        10
weighted avg       0.50      0.50      0.47        10



# Importing our trained model into a pickle file(Levofloxacin)

In [296]:
filename = 'trained_model_Levofloxacin.sav'
pickle.dump(My_LR3, open(filename, 'wb'))

In [297]:
# loading the saved model
loaded_model_3 = pickle.load(open('trained_model_Levofloxacin.sav', 'rb'))

In [298]:
input_data = (24,0,0,1,2)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction3 = loaded_model_3.predict(input_data_reshaped)
print(prediction)

if (prediction3[0] == '0'):
    print('The person is Resistance to the Antibiotic.')
elif (prediction3[0] == '1'):
    print('The person is sensitive to the Antibiotic.')
elif (prediction3[0] == '2'):
    print('The person is intermediate to the Antibiotic.')
else:
    print('The person Unknown to the Antibiotic.')

['3']
The person is Resistance to the Antibiotic.


# 4.Spliting the Dataset for Tigecycline

In [299]:
X4=dataset.drop(['Result','Patient_ID','Amikacin','Aztreonam','Levofloxacin','Tigecycline','Colistin'],axis='columns')
X4.head(3)

Age Gender Infection_Source Condition Infection_type
0   78      0                0         0              0
1   50      1                1         1              0
2   73      0                2         1              0

In [300]:
y4=dataset['Tigecycline']
y4.head(3)

0    0
1    0
2    0
Name: Tigecycline, dtype: object

In [301]:
## Splitting of data for training and testing

from sklearn.model_selection import train_test_split
X4_train, X4_test, y4_train, y4_test = train_test_split(X4,y4,test_size=0.2,random_state=10)


# Train our model with Logistic regression (Tigecycline)

In [302]:
from sklearn.linear_model import LogisticRegression
My_LR4=LogisticRegression()
My_LR4.fit(X4_train, y4_train)

LogisticRegression()

In [303]:
y_pred4=My_LR4.predict(X4_test)

In [304]:
My_LR4.predict([[55,1,2,2,2]])

array(['0'], dtype=object)

In [305]:
My_LR4.score(X4_test,y4_test)

0.5

In [306]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)

scores4=cross_val_score(LogisticRegression(), X4, y4, cv=cv)
print(scores)

[0.8 0.6 0.5 0.5 0.6]


In [307]:
avg_score = np.mean(scores4)
print(avg_score)

0.52


In [308]:
from sklearn.metrics import classification_report
print(classification_report(y4_test,y_pred4))

              precision    recall  f1-score   support

           0       0.57      0.67      0.62         6
           3       0.33      0.25      0.29         4

    accuracy                           0.50        10
   macro avg       0.45      0.46      0.45        10
weighted avg       0.48      0.50      0.48        10



# Importing our trained model into a pickle file(Tigecycline)

In [309]:
filename = 'trained_model_Tigecycline.sav'
pickle.dump(My_LR4, open(filename, 'wb'))

In [310]:
# loading the saved model
loaded_model_4 = pickle.load(open('trained_model_Tigecycline.sav', 'rb'))

In [311]:
input_data = (21,1,4,1,1)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction4 = loaded_model_4.predict(input_data_reshaped)
print(prediction)

if (prediction4[0] == '0'):
    print('The person is Resistance to the Antibiotic.')
elif (prediction4[0] == '1'):
    print('The person is sensitive to the Antibiotic.')
elif (prediction4[0] == '2'):
    print('The person is intermediate to the Antibiotic.')
else:
    print('The person Unknown to the Antibiotic.')

['3']
The person is Resistance to the Antibiotic.



# 5.Spliting the Dataset for Colistin

In [312]:
X5=dataset.drop(['Result','Patient_ID','Amikacin','Aztreonam','Levofloxacin','Tigecycline','Colistin'],axis='columns')
X5.head(3)

Age Gender Infection_Source Condition Infection_type
0   78      0                0         0              0
1   50      1                1         1              0
2   73      0                2         1              0

In [313]:
y5=dataset['Colistin']
y5.head(3)

0    2
1    2
2    2
Name: Colistin, dtype: object

In [314]:
## Splitting of data for training and testing

from sklearn.model_selection import train_test_split
X5_train, X5_test, y5_train, y5_test = train_test_split(X5,y5,test_size=0.2,random_state=10)


# Train our model with Logistic regression (Colistin)

In [315]:
from sklearn.linear_model import LogisticRegression
My_LR5=LogisticRegression()
My_LR5.fit(X5_train, y5_train)

LogisticRegression()

In [316]:
y_pred5=My_LR5.predict(X5_test)

In [317]:
My_LR5.predict([[55,1,2,2,2]])

array(['2'], dtype=object)

In [318]:
My_LR5.score(X5_test,y5_test)

0.9

In [319]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)

scores5=cross_val_score(LogisticRegression(), X5, y5, cv=cv)
print(scores)

[0.8 0.6 0.5 0.5 0.6]


In [320]:
avg_score = np.mean(scores5)
print(avg_score)

0.8


In [321]:
from sklearn.metrics import classification_report
print(classification_report(y5_test,y_pred5))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           2       0.90      1.00      0.95         9

    accuracy                           0.90        10
   macro avg       0.45      0.50      0.47        10
weighted avg       0.81      0.90      0.85        10



# Importing our trained model into a pickle file(Colistin)

In [322]:
filename = 'trained_model_Colistin.sav'
pickle.dump(My_LR5, open(filename, 'wb'))

In [323]:
# loading the saved model
loaded_model_5 = pickle.load(open('trained_model_Colistin.sav', 'rb'))

In [324]:
input_data = (21,1,0,0,0)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction5 = loaded_model_5.predict(input_data_reshaped)
print(prediction)

if (prediction5[0] == '0'):
    print('The person is Resistance to the Antibiotic.')
elif (prediction5[0] == '1'):
    print('The person is sensitive to the Antibiotic.')
elif (prediction5[0] == '2'):
    print('The person is intermediate to the Antibiotic.')
else:
    print('The person Unknown to the Antibiotic.')

['3']
The person is intermediate to the Antibiotic.
